model:
  name: resnet18
  num_classes: 2  # binary classification: pneumonia vs normal
  freeze_base: true

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  device: "cuda"

data:
  data_dir: "data/raw/chest_xray"
  image_size:   [224, 224] # width, height --> only because i use CPU power
  use_medical_transforms: true

evaluation:
  metrics: ["accuracy", "precision", "recall", "f1_score"]
